apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxoniumbackend
  labels:
    app: taxoniumbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxoniumbackend
  template:
    metadata:
      labels:
        app: taxoniumbackend
    spec:
      containers:
        - name: taxoniumbackend
          image: theosanderson/taxonium:master
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 180
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
