name: Electron build/release

on: 
  push:
  workflow_call:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build Electron app with electron-builder
        run: |
          cd taxonium_electron
          yarn install
          yarn make --arch universal
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: List output
        run: |
          cd taxonium_electron
          cd out/make/squirrel.windows
          find .

      - name: Store artifact
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: taxonium_electron/out/make/Taxonium-1.0.1-universal.dmg

  build-win:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build Electron app with electron-builder
        run: |
          cd taxonium_electron
          yarn install
          yarn make --win --arch=x64

      - name: List output
        run: |
          cd taxonium_electron
          cd out/make
          dir
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Store artifact
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: taxonium_electron/out/make/Taxonium-1.0.1-setup.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build Electron app with electron-builder
        run: |
          cd taxonium_electron
          yarn install
          yarn make --linux --arch=x64
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: List output
        run: |
          cd taxonium_electron
          cd out/make
          find .

      - name: Store artifact
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: taxonium_electron/out/make/