name: Electron build/release

on: 
  push:
  workflow_call:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build Electron app with electron-builder
        run: |
          cd taxonium_electron
          yarn install
          yarn electron-builder -m
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
          working_directory: taxonium_electron/dist/
          files: |
            taxonium_electron/dist/Taxonium*
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  
