name: Frontend

on:
   workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
      - uses: actions/setup-node@v3
        with:
          node-version: 17.5
      - name: Start NPM server
        run: |
          cd taxonium_web_client
          npm install -g yarn
          yarn install
          yarn build
          cd build