name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: NODE_OPTIONS='--max-old-space-size=4096' yarn install
        working-directory: ./taxonium_website
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./taxonium_website
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./taxonium_website
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./taxonium_website/playwright-report/
          retention-days: 30
