name: Release Taxonium Component

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Release it
        run: |
          cd taxonium_component
          yarn install
          yarn build
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          yarn release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
